sudo: false
script:
- make install && make test && make provision
- make tidy
language: node_js
node_js:
- 0.12.*
after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy
notifications:
  slack:
    secure: YftJ7Q4x5wuBbZnL/++JQ9p3kISsRosBak6USCx7QajnbqQFpRNm0jJN4bDLjscf+Yja6fbcSeAyqlT1MI7AogYTEXkpOm7xmrK2AdvRLjpFbkXJyxQWzjU6o8GP8HaH5R8GlA3GroLFI+6PKxJzmavGHrC4CwfLVBipFaFwSxI=
